import = ["/home/kei/.config/alacritty/current-theme.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 7

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "_"
mods = "Control"

[scrolling]
history = 5000

# [visual_bell]
# animation = "EaseOutExpo"
# color = "0xffffff"
# duration = 1

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
